package dev.tomasek.bdaycasino.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFB71C1C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFCDD2)
val md_theme_light_onPrimaryContainer = Color(0xFFB71C1C)
val md_theme_light_secondary = Color(0xFF4CAF50)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC8E6C9)
val md_theme_light_onSecondaryContainer = Color(0xFF4CAF50)
val md_theme_light_tertiary = Color(0xFFFFEB3B)
val md_theme_light_onTertiary = Color(0xFF000000)
val md_theme_light_tertiaryContainer = Color(0xFFFFF9C4)
val md_theme_light_onTertiaryContainer = Color(0xFFFFEB3B)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_errorContainer = Color(0xFFFFCDD2)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFFD32F2F)
val md_theme_light_background = Color(0xFFFFF8E1)
val md_theme_light_onBackground = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFE0B2)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFD7CCC8)
val md_theme_light_onSurfaceVariant = Color(0xFF5D4037)
val md_theme_light_outline = Color(0xFF8D6E63)
val md_theme_light_inverseOnSurface = Color(0xFFFFF8E1)
val md_theme_light_inverseSurface = Color(0xFF3E2723)
val md_theme_light_inversePrimary = Color(0xFFFF5252)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFB71C1C)
val md_theme_light_outlineVariant = Color(0xFFBCAAA4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFF5252)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFFB71C1C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFCDD2)
val md_theme_dark_secondary = Color(0xFF81C784)
val md_theme_dark_onSecondary = Color(0xFF2E7D32)
val md_theme_dark_secondaryContainer = Color(0xFF2E7D32)
val md_theme_dark_onSecondaryContainer = Color(0xFFC8E6C9)
val md_theme_dark_tertiary = Color(0xFFFFF176)
val md_theme_dark_onTertiary = Color(0xFFFBC02D)
val md_theme_dark_tertiaryContainer = Color(0xFFFBC02D)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFF9C4)
val md_theme_dark_error = Color(0xFFE57373)
val md_theme_dark_errorContainer = Color(0xFFD32F2F)
val md_theme_dark_onError = Color(0xFFB71C1C)
val md_theme_dark_onErrorContainer = Color(0xFFFFCDD2)
val md_theme_dark_background = Color(0xFF3E2723)
val md_theme_dark_onBackground = Color(0xFFFFF8E1)
val md_theme_dark_surface = Color(0xFF4E342E)
val md_theme_dark_onSurface = Color(0xFFFFF8E1)
val md_theme_dark_surfaceVariant = Color(0xFF5D4037)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7CCC8)
val md_theme_dark_outline = Color(0xFF8D6E63)
val md_theme_dark_inverseOnSurface = Color(0xFF3E2723)
val md_theme_dark_inverseSurface = Color(0xFFFFF8E1)
val md_theme_dark_inversePrimary = Color(0xFFB71C1C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFF5252)
val md_theme_dark_outlineVariant = Color(0xFF5D4037)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF825500)
